name = 'fluidity'
license = 'MIT'
licenselink = 'https://github.com/wayjam/hugo-theme-fluidity/blob/master/LICENSE'
description = 'A fluid and responsive Hugo theme.'
homepage = 'https://github.com/wayjam/hugo-theme-fluidity'
tags = ["blog", "fluent", "clean", "simple", "light", "dark" ,"writing", "syntax highlighting", "archives"]
features = ["blog", "responsive", "social media", "archives"]
[author]
  name = 'WayJam So'
  homepage = 'https://github.com/wayjam'